# Generated by Django 3.2.4 on 2021-06-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210615_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='Contact',
        ),
    ]
